use_frameworks!
source 'https://github.com/Arabrellaxy/XYSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'SalesManLogin_Example' do
    pod 'SalesManLogin',:path => '../'
  pod 'SalesManNetwork'
  pod 'SalesManGlobal'
  pod 'SalesManDataStorage'
  target 'SalesManLogin_Tests' do
    inherit! :search_paths

    
  end
end
